"""Initial migration

Revision ID: 397a5577e0a6
Revises: 
Create Date: 2024-12-16 23:41:00.966378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397a5577e0a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    # ### end Alembic commands ###
