"""Added primary port_id

Revision ID: 511cbcefa5d7
Revises: 5dd1de21aba1
Create Date: 2024-12-17 12:50:03.968016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '511cbcefa5d7'
down_revision = '5dd1de21aba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('port_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('port_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
